rest_api:
  listen: 0.0.0.0
auth:
  host: auth
db_uri: postgresql://asterisk:proformatique@postgres/asterisk
bus:
  host: rabbitmq
celery:
  broker: amqp://guest:guest@rabbitmq:5672
enabled_plugins:
  sentinel: True
service_discovery:
  enabled: false
hook_max_attempts: 3
