- name: Require tox_envlist variable
  fail:
    msg: tox_envlist is required for this role
  when: tox_envlist is not defined

- name: Run tox without tests
  command: "{{ tox_executable }} --notest -e{{ tox_envlist }}"
  args:
    chdir: "{{ zuul_work_dir }}"
  environment: "{{ tox_environment|combine(tox_constraints_env|default({})) }}"

- name: Install any sibling python packages
  tox_install_sibling_packages:
    tox_envlist: "{{ tox_envlist }}"
    tox_constraints_file: "{{ tox_constraints_file | default(omit) }}"
    project_dir: "{{ zuul_work_dir }}"
    projects: "{{ zuul.projects.values() | list | json_query(projects_filter) }}"
  vars:
    projects_filter: "[?name!='{{ zuul.project.name }}']"

- name: Install any sibling python packages into docker compose configuration
  docker_sibling_packages:
    tox_envlist: "{{ tox_envlist }}"
    project_dir: "{{ zuul_work_dir }}"
    projects: "{{ zuul.projects.values() | list | json_query(projects_filter) }}"
    services: "{{ docker_compose_services_override | list }}"
  vars:
    projects_filter: "[?name!='{{ zuul.project.name }}']"
  register: docker_sibling_results

- name: Set docker-compose override location env
  set_fact:
   docker_compose_override_env:
     WAZO_TEST_DOCKER_OVERRIDE_EXTRA: "{{ docker_sibling_results.file }}"

- name: Emit docker compose override file
  debug:
    msg: "Docker compose override file contents: {{ docker_sibling_results.contents }}"

- name: Emit tox command
  debug:
    msg: "Running tox: {{ tox_executable }} -e{{ tox_envlist }} {{ tox_extra_args }}"

- name: Run tox
  args:
    chdir: "{{ zuul_work_dir }}"
  environment: "{{ tox_environment|combine(docker_compose_override_env)|combine(tox_constraints_env|default({})) }}"
  command: "{{ tox_executable }} -e{{ tox_envlist }} {{ tox_extra_args }}"
