- job:
    name: tox-integration
    parent: tox
    description: |
      Run integration tests.

      Uses tox with the ``integration`` environment.
    vars:
      tox_target: integration
    nodeset:
      nodes:
        - name: test-node
          label: debian9-vm

- project:
    check:
      jobs:
        - tox-linters
        - tox-py35
        - tox-integration
    gate:
      jobs:
        - tox-linters
        - tox-py35
        - tox-integration
