- job:
    name: tox-integration
    parent: tox
    description: |
      Run integration tests.

      Uses tox with the ``integration`` environment.
    vars:
      tox_envlist: integration

- project:
    check:
      jobs:
        - tox-linters
        - tox-py35
        - tox-integration
    gate:
      jobs:
        - tox-linters
        - tox-py35
        - tox-integration
