version: '3'
services:
  sync:
    image: wazopbx/wait
    environment:
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"

  auth:
    image: "wazopbx/wazo-auth-mock"
    ports:
      - "9497"
    volumes:
      - "./ssl:/usr/local/share/ssl"

  third-party-http:
    # image: jamesdbloom/mockserver:mockserver-5.2.3
    image: sileht/mockserver
    ports:
      - "1080"

  fcm.googleapis.com:
    # image: jamesdbloom/mockserver:mockserver-5.2.3
    # command: ["/bin/bash", "-xv", "/opt/mockserver/run_mockserver.sh", "-logLevel", "DEBUG", "-serverPort", "443", "-proxyPort", "1090", "-genericJVMOptions", "-Dmockserver.sslCertificateDomainName='fcm.googleapis.com'"]
    image: sileht/mockserver
    command: ["-logLevel", "DEBUG", "-serverPort", "443", "-proxyPort", "1090", "-genericJVMOptions", "-Dmockserver.sslCertificateDomainName='fcm.googleapis.com'"]
    user: root
    ports:
      - "443"

  postgres:
    image: wazopbx/wazo-webhookd-db
    ports:
      - "5432"

  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"

  webhookd:
    image: "wazo-webhookd-test"
    environment:
      XIVO_UUID: "cd030e68-ace9-4ad4-bc4e-13c8dec67898"
    volumes:
      - "../..:/usr/src/wazo-webhookd"
      - "./ssl:/usr/local/share/ssl"
      - "./etc/wazo-webhookd/conf.d/50-default-config.yml:/etc/wazo-webhookd/conf.d/50-default-config.yml"
      - "./keys/wazo-webhookd-key.yml:/var/lib/wazo-auth-keys/wazo-webhookd-key.yml"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/usr/local/lib/python3.5/site-packages/xivo"
    ports:
      - "9300"
